---
- name: Ensure required packages are installed.
  apt:
    name:
      - pacemaker
      - corosync
      - fence-agents
    state: present
    update_cache: yes

- name: Send vendor ocf resources
  include_tasks: send_vendor_ocf_resources.yml
  with_items: "{{ vendor_custom_resources }}"
  loop_control: 
    loop_var: resource

- name: Send custom ocf resources
  include_tasks: send_custom_ocf_resources.yml
  with_dict: "{{ custom_ocf_resources }}"
  loop_control: 
    loop_var: resource

- name: Configure cluster
  include_tasks: configure_cluster.yml
