- name: Ensure resource directory
  file:
    path: "/usr/lib/ocf/resource.d/{{ resource.key }}"
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Send resources
  copy:
    dest: "/usr/lib/ocf/resource.d/{{ resource.key }}/{{ item.key }}"
    content: "{{ item.value }}"
    owner: root
    group: root
    mode: "0755"
  with_dict: "{{ resource.value }}"
